# Generated by Django 2.2.1 on 2021-05-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210526_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image1',
            new_name='header_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='header_image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='header_image3',
        ),
    ]
