# Generated by Django 2.2.1 on 2021-05-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='header_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
